/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/helmet.glb 
Author: 3DWorkbench (https://sketchfab.com/3DWorkbench)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/black-helmet-fb2230b152824463a75e903d38d035a8
Title: Black helmet
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/helmet.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-2.634, -17.631, -33.11]}>
          <mesh geometry={nodes.parts_parts_0.geometry} material={materials.parts} />
          <mesh geometry={nodes.parts_L2_0.geometry} material={materials.material} />
          <mesh geometry={nodes.parts_L1_0.geometry} material={materials.material_2} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/helmet.glb')
